id: display_data_firestore
learningObjectives:
  - Retrieve and display real-time data from Firestore in your app.
hints:
  - Here's more on viewing data [in
    Firestore](https://firebase.google.com/docs/firestore/query-data/get-data).
  - Check this [tutorial](https://www.youtube.com/watch?v=KmH5ahYgiCA) for
    real-time updates in Firestore.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: >-
              Let's implement real-time data retrieval from Cloud Firestore! This involves two key steps:
              1. Creating a query to fetch restaurants
              2. Adding a snapshot listener for real-time updates

              First, head to `scripts/FriendlyEats.Data.js` and replace `getAllRestaurants`:

              ```javascript
              FriendlyEats.prototype.getAllRestaurants = function(renderer) {
                var query = firebase.firestore()
                  .collection('restaurants')
                  .orderBy('avgRating', 'desc')
                  .limit(50);
                this.getDocumentsInQuery(query, renderer);
              };
              ```

              This query will fetch up to 50 restaurants, ordered by their average rating.

              Now, add a snapshot listener in `getDocumentsInQuery` to handle real-time updates:

              ```javascript
              FriendlyEats.prototype.getDocumentsInQuery = function(query, renderer) {
                query.onSnapshot(function(snapshot) {
                  if (!snapshot.size) return renderer.empty(); // Display "There are no restaurants".
                  snapshot.docChanges().forEach(function(change) {
                    if (change.type === 'removed') {
                      renderer.remove(change.doc);
                    } else {
                      renderer.display(change.doc);
                    }
                  });
                });
              };
              ```

              The snapshot listener will:
              - Initially load all matching restaurants
              - Automatically update the UI when restaurants are added/modified/deleted
              - Remove restaurants from the UI when deleted in Firestore

              Try it out:
              1. Load the app to see your restaurants
              2. Make changes in the Firebase Console
              3. Watch the app update in real-time!
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
