id: strengthen_app_security
learningObjectives:
  - Secure app data with Firebase security rules.
hints:
  - Get started with Firebase security rules in the [official documentation](https://firebase.google.com/docs/firestore/security/get-started).
  - Learn more from this [video tutorial](https://www.youtube.com/watch?v=MGkDFsOWut0) on Firebase security.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: >-
              Let's secure your app with proper Firebase rules. Update your `firestore.rules` file:

              ```
              rules_version = '2';

              service cloud.firestore {
                function unchanged(key) {
                  return (key in resource.data) && (key in request.resource.data) && (resource.data[key] == request.resource.data[key]);
                }

                match /databases/{database}/documents {
                  match /restaurants/{restaurantId} {
                    allow read: if request.auth != null;
                    allow create: if request.auth != null;
                    allow update: if request.auth != null &&
                      (request.resource.data.keys() == resource.data.keys()) && unchanged('name');
                    
                    match /ratings/{ratingId} {
                      allow read: if request.auth != null;
                      allow create: if request.auth != null &&
                        request.resource.data.userId == request.auth.uid;
                    }
                  }
                }
              }
              ```

              Deploy these rules with: `firebase deploy --only firestore:rules`
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: >-
                Great work! You've successfully secured your app with Firebase rules.
                These rules ensure:
                - Only authenticated users can read and create restaurants
                - Restaurant names can't be changed after creation
                - Users can only create ratings under their own user ID
                
                Your app is now protected against unauthorized access! 🔒✨
      - actionId: finish_step
